import {
    MdSchool, MdStar, MdStarBorder, MdWork, MdCheckCircle,
    MdEmojiEvents, MdBarChart, MdPerson, MdVerified,
} from "react-icons/md";
import { useGetMyReportCardQuery, useGetMyStudentProfileQuery } from "../../../redux/api/studentApi";

// ── Helpers ───────────────────────────────────────────────────────────────────
const gradeColor = (g = "") => {
    const u = g.toUpperCase();
    if (["A+", "A"].includes(u))  return "bg-green-50 text-green-700 border border-green-200";
    if (["B+", "B"].includes(u))  return "bg-blue-50 text-blue-700 border border-blue-200";
    if (["C+", "C"].includes(u))  return "bg-yellow-50 text-yellow-700 border border-yellow-200";
    return "bg-gray-100 text-gray-500 border border-gray-200";
};

const readinessBadge = (s = "") => {
    if (s === "Ready")     return "bg-green-50 text-green-700 border border-green-200";
    if (s === "Not Ready") return "bg-red-50 text-red-500 border border-red-200";
    return "bg-gray-100 text-gray-500 border border-gray-200";
};

const ProgressBar = ({ pct, color = "bg-orange-400" }) => (
    <div className="w-full bg-gray-100 rounded-full h-1.5 mt-1">
        <div className={`h-1.5 rounded-full transition-all duration-500 ${color}`} style={{ width: `${Math.min(pct, 100)}%` }} />
    </div>
);

// ── Section Header ─────────────────────────────────────────────────────────────
const SectionHeader = ({ icon, title, iconBg }) => (
    <div className="px-5 py-4 border-b border-gray-50 flex items-center gap-2">
        <div className={`w-7 h-7 rounded-lg flex items-center justify-center ${iconBg}`}>{icon}</div>
        <h3 className="text-sm font-bold text-gray-800">{title}</h3>
    </div>
);

// ── Stars ─────────────────────────────────────────────────────────────────────
const Stars = ({ value, max = 5 }) => (
    <div className="flex items-center gap-0.5">
        {Array.from({ length: max }, (_, i) =>
            i < value
                ? <MdStar key={i} size={13} className="text-orange-400" />
                : <MdStarBorder key={i} size={13} className="text-gray-200" />
        )}
    </div>
);

// ── Empty State ───────────────────────────────────────────────────────────────
const EmptyState = ({ icon, message }) => (
    <div className="flex flex-col items-center justify-center py-16 text-center">
        <div className="w-14 h-14 rounded-2xl bg-gray-50 flex items-center justify-center mb-3">{icon}</div>
        <p className="text-sm font-semibold text-gray-500">{message}</p>
        <p className="text-xs text-gray-400 mt-1">Your report card will appear here once it is generated by the faculty.</p>
    </div>
);

// ── Main ──────────────────────────────────────────────────────────────────────
export default function StudentReportCard() {
    const { data: rcData, isLoading: rcLoading } = useGetMyReportCardQuery();
    const { data: profileData, isLoading: profileLoading } = useGetMyStudentProfileQuery();

    const isLoading = rcLoading || profileLoading;

    if (isLoading) return (
        <div className="flex justify-center pt-20">
            <div className="w-8 h-8 border-2 border-orange-500 border-t-transparent rounded-full animate-spin" />
        </div>
    );

    const raw  = profileData?.data || {};
    const rc   = rcData?.data || null;
    const name = `${raw.firstName || ""} ${raw.lastName || ""}`.trim() || "Student";
    const initials = name.split(" ").map(n => n[0]).join("").slice(0, 2).toUpperCase();

    return (
        <div className="space-y-5">

            {/* ── Header Card ── */}
            <div className="bg-white border border-gray-100 rounded-2xl overflow-hidden shadow-sm">
                <div className="h-1.5 w-full bg-orange-500" />
                <div className="p-5">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                        <div>
                            <h2 className="text-base font-bold text-gray-900">Report Card</h2>
                            <p className="text-xs text-gray-400 mt-0.5">
                                {rc ? `Batch ${rc.batchYear} · Generated by ${rc.generatedByName}` : "No report card generated yet"}
                            </p>
                        </div>
                        <div className="flex items-center gap-2 flex-wrap">
                            {rc?.overallGrade && (
                                <span className={`text-xs font-bold px-3 py-1 rounded-full ${gradeColor(rc.overallGrade)}`}>
                                    Grade: {rc.overallGrade}
                                </span>
                            )}
                            {rc?.isFinalReport && (
                                <span className="text-xs font-bold px-3 py-1 rounded-full bg-green-50 text-green-700 border border-green-200 flex items-center gap-1">
                                    <MdVerified size={11} /> Final Report
                                </span>
                            )}
                        </div>
                    </div>

                    {/* Student Info Pills */}
                    <div className="flex items-center gap-3 mt-4 flex-wrap">
                        <div className="flex items-center gap-2">
                            {raw.image ? (
                                <img src={raw.image} alt={name} className="w-8 h-8 rounded-xl object-cover border border-gray-100" />
                            ) : (
                                <div className="w-8 h-8 rounded-xl bg-orange-50 text-orange-500 flex items-center justify-center text-sm font-bold border border-orange-100">
                                    {initials}
                                </div>
                            )}
                            <span className="text-sm font-bold text-gray-800">{name}</span>
                            <MdVerified size={13} className="text-blue-500" />
                        </div>
                        {raw.prkey && (
                            <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
                                {raw.prkey}
                            </span>
                        )}
                        {raw.currentLevelId?.name && (
                            <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-orange-50 text-orange-600 border border-orange-100">
                                {raw.currentLevelId.name}
                            </span>
                        )}
                        {raw.currentSubLevelId?.name && (
                            <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-violet-50 text-violet-600 border border-violet-100">
                                {raw.currentSubLevelId.name}
                            </span>
                        )}
                    </div>
                </div>
            </div>

            {/* ── No Report Card ── */}
            {!rc ? (
                <div className="bg-white border border-gray-100 rounded-2xl shadow-sm">
                    <EmptyState
                        icon={<MdSchool size={28} className="text-gray-300" />}
                        message="Report card not available yet"
                    />
                </div>
            ) : (
                <>
                    {/* ── Summary Stats ── */}
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
                        {[
                            {
                                label: "Soft Skills",
                                value: `${rc.softSkills?.totalSoftSkillMarks ?? 0}`,
                                sub: `/ ${rc.softSkills?.categories?.reduce((s, c) => s + (c.maxMarks || 10), 0) || 50} marks`,
                                iconBg: "bg-orange-50",
                                icon: <MdStar size={20} className="text-orange-500" />,
                                valueColor: "text-orange-500",
                            },
                            {
                                label: "Discipline",
                                value: `${rc.discipline?.totalDisciplineMarks ?? 0}`,
                                sub: `/ ${rc.discipline?.categories?.reduce((s, c) => s + (c.maxMarks || 10), 0) || 30} marks`,
                                iconBg: "bg-violet-50",
                                icon: <MdCheckCircle size={20} className="text-violet-500" />,
                                valueColor: "text-violet-600",
                            },
                            {
                                label: "Overall Grade",
                                value: rc.overallGrade || "—",
                                sub: rc.isFinalReport ? "Final Report" : "In Progress",
                                iconBg: "bg-blue-50",
                                icon: <MdBarChart size={20} className="text-blue-500" />,
                                valueColor: "text-blue-600",
                            },
                            {
                                label: "Placement Ready",
                                value: rc.careerReadiness?.placementReady || "—",
                                sub: rc.careerReadiness?.aptitudeStatus || "",
                                iconBg: "bg-green-50",
                                icon: <MdWork size={20} className="text-green-500" />,
                                valueColor: rc.careerReadiness?.placementReady === "Ready" ? "text-green-600" : "text-red-500",
                            },
                        ].map(({ label, value, sub, iconBg, icon, valueColor }) => (
                            <div key={label} className="bg-white border border-gray-100 rounded-2xl p-4 shadow-sm flex items-center gap-4">
                                <div className={`w-11 h-11 rounded-xl flex items-center justify-center flex-shrink-0 ${iconBg}`}>{icon}</div>
                                <div className="min-w-0">
                                    <p className="text-[11px] text-gray-400 font-medium">{label}</p>
                                    <p className={`text-xl font-bold leading-tight ${valueColor}`}>{value}</p>
                                    {sub && <p className="text-[10px] text-gray-400 mt-0.5">{sub}</p>}
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* ── 2 Column Layout ── */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">

                        {/* Soft Skills */}
                        {rc.softSkills?.categories?.length > 0 && (
                            <div className="bg-white border border-gray-100 rounded-2xl shadow-sm">
                                <SectionHeader
                                    icon={<MdStar size={15} className="text-orange-500" />}
                                    title={rc.softSkills.sectionTitle || "Soft Skills Evaluation"}
                                    iconBg="bg-orange-50"
                                />
                                <div className="p-5 space-y-4">
                                    {rc.softSkills.categories.map((cat, i) => {
                                        const pct = Math.round(((cat.score || 0) / (cat.maxMarks || 10)) * 100);
                                        return (
                                            <div key={i}>
                                                <div className="flex items-center justify-between">
                                                    <p className="text-xs font-semibold text-gray-700">{cat.title}</p>
                                                    <span className="text-xs font-bold text-gray-600">
                                                        {cat.score ?? 0}<span className="text-gray-400 font-normal">/{cat.maxMarks || 10}</span>
                                                    </span>
                                                </div>
                                                <ProgressBar pct={pct} color="bg-orange-400" />
                                                {cat.subcategories?.length > 0 && (
                                                    <div className="flex flex-wrap gap-1.5 mt-2">
                                                        {cat.subcategories.map((s, j) => (
                                                            <span key={j} className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${
                                                                s.value
                                                                    ? "bg-green-50 text-green-600 border-green-100"
                                                                    : "bg-gray-50 text-gray-400 border-gray-200"
                                                            }`}>
                                                                {s.value ? "✓" : "✗"} {s.name}
                                                            </span>
                                                        ))}
                                                    </div>
                                                )}
                                            </div>
                                        );
                                    })}
                                    <div className="mt-2 pt-3 border-t border-gray-50 flex items-center justify-between">
                                        <p className="text-xs font-bold text-gray-600">Total Soft Skill Marks</p>
                                        <span className="text-sm font-bold text-orange-500">{rc.softSkills.totalSoftSkillMarks ?? 0}</span>
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* Discipline */}
                        {rc.discipline?.categories?.length > 0 && (
                            <div className="bg-white border border-gray-100 rounded-2xl shadow-sm">
                                <SectionHeader
                                    icon={<MdCheckCircle size={15} className="text-violet-500" />}
                                    title={rc.discipline.sectionTitle || "Discipline Evaluation"}
                                    iconBg="bg-violet-50"
                                />
                                <div className="p-5 space-y-4">
                                    {rc.discipline.categories.map((cat, i) => {
                                        const pct = Math.round(((cat.score || 0) / (cat.maxMarks || 10)) * 100);
                                        return (
                                            <div key={i}>
                                                <div className="flex items-center justify-between">
                                                    <p className="text-xs font-semibold text-gray-700">{cat.title}</p>
                                                    <span className="text-xs font-bold text-gray-600">
                                                        {cat.score ?? 0}<span className="text-gray-400 font-normal">/{cat.maxMarks || 10}</span>
                                                    </span>
                                                </div>
                                                <ProgressBar pct={pct} color="bg-violet-400" />
                                                {cat.subcategories?.length > 0 && (
                                                    <div className="flex flex-wrap gap-1.5 mt-2">
                                                        {cat.subcategories.map((s, j) => (
                                                            <span key={j} className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${
                                                                s.value
                                                                    ? "bg-green-50 text-green-600 border-green-100"
                                                                    : "bg-gray-50 text-gray-400 border-gray-200"
                                                            }`}>
                                                                {s.value ? "✓" : "✗"} {s.name}
                                                            </span>
                                                        ))}
                                                    </div>
                                                )}
                                            </div>
                                        );
                                    })}
                                    <div className="mt-2 pt-3 border-t border-gray-50 flex items-center justify-between">
                                        <p className="text-xs font-bold text-gray-600">Total Discipline Marks</p>
                                        <span className="text-sm font-bold text-violet-600">{rc.discipline.totalDisciplineMarks ?? 0}</span>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* ── Technical Skills ── */}
                    {rc.technicalSkills?.length > 0 && (
                        <div className="bg-white border border-gray-100 rounded-2xl shadow-sm">
                            <SectionHeader
                                icon={<MdBarChart size={15} className="text-blue-500" />}
                                title="Technical Skills"
                                iconBg="bg-blue-50"
                            />
                            <div className="p-5">
                                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                                    {rc.technicalSkills.map((skill, i) => (
                                        <div key={i} className="bg-gray-50 rounded-xl p-3.5 border border-gray-100 hover:border-blue-100 hover:bg-blue-50/30 transition-all duration-150">
                                            <p className="text-xs font-bold text-gray-800 mb-2">{skill.skillName}</p>
                                            <div className="space-y-1.5">
                                                <div className="flex items-center justify-between">
                                                    <span className="text-[10px] text-gray-400">Theory</span>
                                                    <Stars value={skill.theoryMarks} />
                                                </div>
                                                <div className="flex items-center justify-between">
                                                    <span className="text-[10px] text-gray-400">Practical</span>
                                                    <Stars value={skill.practicalMarks} />
                                                </div>
                                            </div>
                                            {skill.totalPercentage > 0 && (
                                                <>
                                                    <ProgressBar pct={skill.totalPercentage} color="bg-blue-400" />
                                                    <p className="text-[10px] text-gray-400 mt-1">{skill.totalPercentage}% overall</p>
                                                </>
                                            )}
                                            {skill.remark && (
                                                <p className="text-[10px] text-gray-500 mt-1.5 italic">"{skill.remark}"</p>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    )}

                    {/* ── Career Readiness + Academic + Co-Curricular ── */}
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">

                        {/* Career Readiness */}
                        {rc.careerReadiness && (
                            <div className="bg-white border border-gray-100 rounded-2xl shadow-sm">
                                <SectionHeader
                                    icon={<MdWork size={15} className="text-green-500" />}
                                    title="Career Readiness"
                                    iconBg="bg-green-50"
                                />
                                <div className="p-4 space-y-2">
                                    {[
                                        { label: "Resume", value: rc.careerReadiness.resumeStatus },
                                        { label: "LinkedIn", value: rc.careerReadiness.linkedinStatus },
                                        { label: "Aptitude", value: rc.careerReadiness.aptitudeStatus },
                                        { label: "Placement", value: rc.careerReadiness.placementReady },
                                    ].map(({ label, value }) => (
                                        <div key={label} className="bg-gray-50 rounded-xl px-3 py-2.5 flex items-center justify-between border border-transparent hover:border-green-100 hover:bg-green-50/40 transition-all duration-150">
                                            <p className="text-[10px] font-bold uppercase tracking-wide text-gray-400">{label}</p>
                                            <span className={`text-[11px] font-bold px-2 py-0.5 rounded-full ${readinessBadge(value)}`}>
                                                {value || "—"}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Academic Performance */}
                        {rc.academicPerformance && (
                            <div className="bg-white border border-gray-100 rounded-2xl shadow-sm">
                                <SectionHeader
                                    icon={<MdSchool size={15} className="text-orange-500" />}
                                    title="Academic Performance"
                                    iconBg="bg-orange-50"
                                />
                                <div className="p-4 space-y-2">
                                    {rc.academicPerformance.cgpa > 0 && (
                                        <div className="bg-orange-50 rounded-xl px-3 py-2.5 flex items-center justify-between border border-orange-100">
                                            <p className="text-[10px] font-bold uppercase tracking-wide text-gray-400">CGPA</p>
                                            <span className="text-sm font-bold text-orange-500">{rc.academicPerformance.cgpa}</span>
                                        </div>
                                    )}
                                    {rc.academicPerformance.yearWiseSGPA?.map((y, i) => (
                                        <div key={i} className="bg-gray-50 rounded-xl px-3 py-2.5 flex items-center justify-between border border-transparent hover:border-orange-100 hover:bg-orange-50/30 transition-all duration-150">
                                            <p className="text-[10px] font-bold uppercase tracking-wide text-gray-400">{y.year}</p>
                                            <span className="text-xs font-bold text-gray-700">SGPA {y.sgpa}</span>
                                        </div>
                                    ))}
                                    {!rc.academicPerformance.cgpa && !rc.academicPerformance.yearWiseSGPA?.length && (
                                        <p className="text-xs text-gray-400 text-center py-4">No academic data available</p>
                                    )}
                                </div>
                            </div>
                        )}

                        {/* Co-Curricular */}
                        {rc.coCurricular?.length > 0 && (
                            <div className="bg-white border border-gray-100 rounded-2xl shadow-sm">
                                <SectionHeader
                                    icon={<MdEmojiEvents size={15} className="text-yellow-500" />}
                                    title="Co-Curricular Activities"
                                    iconBg="bg-yellow-50"
                                />
                                <div className="p-4 space-y-2">
                                    {rc.coCurricular.map((item, i) => (
                                        <div key={i} className="bg-gray-50 rounded-xl px-3 py-2.5 border border-transparent hover:border-yellow-100 hover:bg-yellow-50/30 transition-all duration-150">
                                            <div className="flex items-center justify-between mb-0.5">
                                                <span className="text-[10px] font-bold text-yellow-600 uppercase tracking-wide">{item.category}</span>
                                            </div>
                                            <p className="text-xs font-semibold text-gray-800">{item.title}</p>
                                            {item.remark && <p className="text-[10px] text-gray-400 mt-0.5 italic">"{item.remark}"</p>}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* ── Faculty Remark ── */}
                    {rc.facultyRemark && (
                        <div className="bg-white border border-gray-100 rounded-2xl shadow-sm">
                            <SectionHeader
                                icon={<MdPerson size={15} className="text-gray-500" />}
                                title="Faculty Remark"
                                iconBg="bg-gray-50"
                            />
                            <div className="p-5">
                                <p className="text-sm text-gray-700 leading-relaxed italic">"{rc.facultyRemark}"</p>
                                <p className="text-xs text-gray-400 mt-2">— {rc.generatedByName}</p>
                            </div>
                        </div>
                    )}
                </>
            )}
        </div>
    );
}
